In [3]:
import os , pandas as pd, numpy as np 
from unidecode import unidecode
from datetime import datetime

In [3]:
import os

In [5]:
import os

# Lấy đường dẫn đến thư mục hiện tại
current_directory = os.getcwd()

print(f"Thư mục hiện tại là: {current_directory}")

Thư mục hiện tại là: C:\Users\Admin

In [55]:
def check_info_df(data):
    dataframe = pd.DataFrame(index = data.columns)
    dataframe['date_type'] = data.dtypes
    dataframe['count_unique'] = data.nunique()
    dataframe['not_null_value'] = data.count()
    dataframe['null_value'] = data.isnull().sum()
    dataframe['percentage_of_null'] = data.isnull().sum().mean()*100
    return dataframe

In [18]:
path = r'C:\Users\Admin\Downloads\Python x Tableau'
count = 0 
for root, dic , filenames in os.walk(path):
    for filename in filenames :
        file_name_underscore = filename.split('-')[1].split('.')[0].strip().replace(' ','_').lower()
        unidecode_file_name = unidecode(file_name_underscore)
        print("{} = pd.read_csv(r'{}')" .format(unidecode_file_name,os.path.join(root,filename)))

chi_nhanh = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Chi nhánh.csv')
du_lieu_ban_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Dữ liệu bán hàng.csv')
khach_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Khách hàng.csv')
kpi = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - KPI.csv')
nhan_vien = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Nhân viên.csv')
san_pham = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Sản phẩm.csv')

In [19]:
chi_nhanh = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Chi nhánh.csv')
du_lieu_ban_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Dữ liệu bán hàng.csv')
khach_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Khách hàng.csv')
kpi = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - KPI.csv')
nhan_vien = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Nhân viên.csv')
san_pham = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Sản phẩm.csv')

In [264]:
du_lieu_ban_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Dữ liệu bán hàng.csv')

In [499]:
khach_hang = pd.read_csv(r'C:\Users\Admin\Downloads\Python x Tableau\Sale Data Sample.xlsx - Khách hàng.csv')

# Chi Nhánh - Done

In [521]:
chi_nhanh.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\chi_nhanh.csv', encoding = 'utf-16')

# Dữ Liệu Bán Hàng - Cần Sửa

In [265]:
du_lieu_ban_hang.columns = du_lieu_ban_hang.loc[3]

In [35]:
pd.set_option('display.max_columns' , 100)

In [36]:
pd.set_option('display.max_rows' , 100)

In [266]:
du_lieu_ban_hang = du_lieu_ban_hang.loc[4:len(du_lieu_ban_hang)]

In [267]:
du_lieu_ban_hang.columns.name = None

In [268]:
du_lieu_ban_hang

,Ngày hạch toán,Đơn hàng,Mã KH,Mã Sản Phẩm,Số lượng bán,Đơn giá,Doanh thu,Giá vốn hàng hóa,Mã nhân viên bán,Chi nhánh
4,1/3/2017,ĐH0000737,KH-0001,P-001,12/31/1899,11/9/76644,"27,300,000",2/26/50484,NV00078,CN DN
5,1/4/2017,ĐH0000733,KH-0002,P-001,12/31/1899,12/24/62871,"22,269,560",3/9/38483,NV00078,CN DN
6,1/5/2017,ĐH0000734,KH-0002,P-002,12/31/1899,43680840,"43,680,840",2/23/79636,NV00078,CN DN
7,1/6/2017,ĐH0000764,KH-0003,P-003,1,2200000,2200000,1540000,NV00051,CN HCM
8,1/7/2017,ĐH0000768,KH-0002,P-004,1,11264400,11264400,6758640,NV00078,CN HCM
...,...,...,...,...,...,...,...,...,...,...
2635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nguyễn Văn Trưởng,NaN,NaN

In [269]:
# kiểm tra giá trị null
check_info_df(data = du_lieu_ban_hang)

,date_type,count_unique,not_null_value,null_value,percentage_of_null
Ngày hạch toán,object,1399,2624,12,1180.0
Đơn hàng,object,1526,2624,12,1180.0
Mã KH,object,786,2624,12,1180.0
Mã Sản Phẩm,object,799,2624,12,1180.0
Số lượng bán,object,148,2624,12,1180.0
Đơn giá,object,1670,2624,12,1180.0
Doanh thu,object,2015,2624,12,1180.0
Giá vốn hàng hóa,object,2258,2626,10,1180.0
Mã nhân viên bán,object,49,2624,12,1180.0
Chi nhánh,object,3,2624,12,1180.0

In [220]:
# check qua dữ giá trị duy nhất ở mỗi trường dữ liệu
du_lieu_ban_hang.apply(lambda x : x.unique())

Ngày hạch toán      [1/3/2017, 1/4/2017, 1/5/2017, 1/6/2017, 1/7/2...
Đơn hàng            [ĐH0000737, ĐH0000733, ĐH0000734, ĐH0000764, Đ...
Mã KH               [KH-0001, KH-0002, KH-0003, KH-0004, KH-0005, ...
Mã Sản Phẩm         [P-001, P-002, P-003, P-004, P-005, P-006, P-0...
Số lượng bán        [12/31/1899, 1, nan, 2, 1/1/1900, 3, 1/2/1900,...
Đơn giá             [11/9/76644, 12/24/62871, 43680840, 2200000, 1...
Doanh thu           [27,300,000, 22,269,560, 43,680,840, 2200000, ...
Giá vốn hàng hóa    [2/26/50484, 3/9/38483, 2/23/79636, 1540000, 6...
Mã nhân viên bán    [NV00078, NV00051, NV00089, NV00029, NV00061, ...
Chi nhánh                                 [CN DN, CN HCM, CN HN, nan]
dtype: object

In [270]:
# xóa dữ liệu bị trùng
du_lieu_ban_hang.drop_duplicates()

,Ngày hạch toán,Đơn hàng,Mã KH,Mã Sản Phẩm,Số lượng bán,Đơn giá,Doanh thu,Giá vốn hàng hóa,Mã nhân viên bán,Chi nhánh
4,1/3/2017,ĐH0000737,KH-0001,P-001,12/31/1899,11/9/76644,"27,300,000",2/26/50484,NV00078,CN DN
5,1/4/2017,ĐH0000733,KH-0002,P-001,12/31/1899,12/24/62871,"22,269,560",3/9/38483,NV00078,CN DN
6,1/5/2017,ĐH0000734,KH-0002,P-002,12/31/1899,43680840,"43,680,840",2/23/79636,NV00078,CN DN
7,1/6/2017,ĐH0000764,KH-0003,P-003,1,2200000,2200000,1540000,NV00051,CN HCM
8,1/7/2017,ĐH0000768,KH-0002,P-004,1,11264400,11264400,6758640,NV00078,CN HCM
...,...,...,...,...,...,...,...,...,...,...
2629,3/29/2019,ĐH10434,KH-0176,P-018,1.00,"2,930,000.00","2,930,000",1904500,NV00095,CN HCM
2630,3/29/2019,ĐH10434,KH-0176,P-798,12/31/1899,12/13/15041,12/13/15041,4/7/10442,NV00095,CN DN
2631,3/29/2019,ĐH10434,KH-0176,P-799,1.00,"110,000.00","110,000",66000,NV00095,CN HN
2634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kế toán trưởng,NaN,NaN
2639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nguyễn Văn Trưởng,NaN,NaN

In [271]:
#check và kiểm tra các dòng có số giá trị null lớn hơn 8 để tiến hành loại bỏ
row_null_values = du_lieu_ban_hang.isnull().sum(axis=1)
row_null_values[row_null_values>=8].index

Int64Index([22, 23, 57, 58, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639], dtype='int64')

In [272]:
#xóa bỏ dòng có nhiều giá trị null
du_lieu_ban_hang.drop(row_null_values[row_null_values>=8].index , axis =0 , inplace = True)

In [274]:
#convert sang dạng string để thao tác cho dễ hơn nè
list_columns = ['Số lượng bán','Đơn giá','Doanh thu','Giá vốn hàng hóa']
for column in list_columns:
    du_lieu_ban_hang[column] = du_lieu_ban_hang[column].astype('object')

In [275]:
# Tạo back up 
list_columns = ['Số lượng bán','Đơn giá','Doanh thu','Giá vốn hàng hóa']
back_up = pd.DataFrame()
for column in list_columns:
    
    back_up[column] = du_lieu_ban_hang[column].copy()

In [276]:
back_up

     Số lượng bán         Đơn giá      Doanh thu Giá vốn hàng hóa
4      12/31/1899      11/9/76644     27,300,000       2/26/50484
5      12/31/1899     12/24/62871     22,269,560        3/9/38483
6      12/31/1899        43680840     43,680,840       2/23/79636
7               1         2200000        2200000          1540000
8               1        11264400       11264400          6758640
...           ...             ...            ...              ...
2627       20.00    7,525,000.00    150,500,000          97825000
2628    1/14/1900      5/22/19696       97500000         68250000
2629        1.00    2,930,000.00      2,930,000           1904500
2630   12/31/1899     12/13/15041    12/13/15041        4/7/10442
2631        1.00      110,000.00        110,000             66000

[2624 rows x 4 columns]

In [277]:
# định dạng lại giá trị ở các cột chứa số liệu số
list_columns = ['Số lượng bán','Đơn giá','Doanh thu','Giá vốn hàng hóa']
for column in list_columns:
    du_lieu_ban_hang[column] = du_lieu_ban_hang[column].apply(lambda x : x.replace(',','').replace('.00','').strip())

In [280]:
pd.set_option('display.max_rows' ,200)

In [155]:
median_gia_san_pham = matches_sorted[['Mã Sản Phẩm', 'Đơn giá']].groupby('Mã Sản Phẩm' , as_index = False)['Đơn giá'].median().head(200)

In [281]:
# check bộ số liệu ở cột doanh thu có số liệu sai cấu trúc
du_lieu_ban_hang[~( 
                    
                   (du_lieu_ban_hang['Doanh thu'].str.isdecimal()) )].index

Int64Index([ 159,  160,  161,  165,  168,  170,  176,  178,  184,  186,
            ...
            2604, 2609, 2610, 2614, 2616, 2618, 2620, 2624, 2625, 2630],
           dtype='int64', length=516)

In [282]:
# tiến hành xóa bỏ
du_lieu_ban_hang.drop(du_lieu_ban_hang[~( 
                    
                   (du_lieu_ban_hang['Doanh thu'].str.isdecimal()) )].index , axis = 0,inplace = True)

In [283]:
def divide_row (row):
    if row['Doanh thu'] == row['Đơn giá'] and not row['Số lượng bán'].isdecimal():
        return 1
    else:
        return row['Số lượng bán']

In [284]:
du_lieu_ban_hang['Số lượng bán'] = du_lieu_ban_hang.apply(divide_row , axis=1)

In [185]:
du_lieu_ban_hang = du_lieu_ban_hang.apply(divide_row , axis=1)

In [302]:
def check_1_1(row):
    if not isinstance(row['Số lượng bán'] ,int) & row['Số lượng bán'] != 1:
        return 1

In [335]:
du_lieu_ban_hang['Số lượng bán'] = du_lieu_ban_hang['Số lượng bán'].astype('string')

In [295]:
isinstance('12/31/1899' ,int)

False

In [350]:
du_lieu_ban_hang[du_lieu_ban_hang['Số lượng bán'] == '1/1/1900']

,Ngày hạch toán,Đơn hàng,Mã KH,Mã Sản Phẩm,Số lượng bán,Đơn giá,Doanh thu,Giá vốn hàng hóa,Mã nhân viên bán,Chi nhánh
1136,7/18/2016,ĐH0002278,KH-0112,P-341,1/1/1900,3/4/62027,43922000,1/15/86078,NV00002,CN DN
1199,9/19/2016,ĐH0001235,KH-0506,P-502,1/1/1900,7/26/98219,70360000,49252000,NV00061,CN DN
1251,11/10/2016,ĐH0001491,KH-0519,P-517,1/1/1900,9/11/87322,62400000,40560000,NV00046,CN DN
1264,11/23/2016,ĐH0001588,KH-0176,P-521,1/1/1900,6/27/75823,54000000,37800000,NV00081,CN DN
1286,12/15/2016,ĐH0001699,KH-0155,P-527,1/1/1900,49175000,98350000,59010000,NV00009,CN DN
1287,12/16/2016,ĐH0001699,KH-0155,P-528,1/1/1900,9/12/59587,42140000,1/2/76894,NV00009,CN DN
1289,12/18/2016,ĐH0001699,KH-0155,P-530,1/1/1900,8/7/90060,64400000,38640000,NV00009,CN DN
1314,1/12/2017,ĐH0001752,KH-0532,P-432,1/1/1900,6/26/52277,36800000,9/24/67390,NV00064,CN DN
1316,1/14/2017,ĐH0001769,KH-0230,P-542,1/1/1900,6/21/2584,500000,10/25/2789,NV00061,CN DN
1317,1/15/2017,ĐH0001774,KH-0372,P-139,1/1/1900,9/29/9545,5585104,11/22/11074,NV00046,CN DN
1318,1/16/2017,ĐH0000978,KH-0023,P-046,1/1/1900,5/21/50941,35824000,10/20/65653,NV00086,CN DN
1319,1/17/2017,ĐH0004817,KH-0233,P-046,1/1/1900,6/18/47075,33000000,8/25/65145,NV00015,CN DN
1338,2/5/2017,ĐH0004903,KH-0176,P-229,1/1/1900,6/5/3953,1500000,10/19/4774,NV00046,CN DN
1339,2/6/2017,ĐH0004909,KH-0191,P-046,1/1/1900,2/2/46254,32400000,11/28/55124,NV00095,CN DN
1340,2/7/2017,ĐH0004909,KH-0191,P-020,1/1/1900,10/23/7375,4000000,7/22/9018,NV00095,CN DN
1343,2/10/2017,ĐH0004941,KH-0112,P-548,1/1/1900,12/1/54330,38300000,2/5/64817,NV00007,CN DN
1344,2/11/2017,ĐH0004942,KH-0320,P-549,1/1/1900,5/31/21785,14526000,1/15/27751,NV00011,CN DN
1345,2/12/2017,ĐH0004943,KH-0257,P-543,1/1/1900,6/9/21440,14274000,7/11/25348,NV00046,CN DN
1348,2/15/2017,ĐH0004971,KH-0511,P-071,1/1/1900,12/17/5869,2900000,12/15/6663,NV00046,CN DN
1353,2/20/2017,ĐH0004990,KH-0251,P-015,1/1/1900,4/14/12249,7560000,2/22/14319,NV00068,CN DN
1355,2/22/2017,ĐH0000013,KH-0265,P-552,1/1/1900,54220000,108440000,75908000,NV00009,CN DN
1356,2/23/2017,ĐH0000010,KH-0207,P-253,1/1/1900,2/11/4364,1800000,12/7/4856,NV00068,CN DN
1360,2/27/2017,ĐH0000051,KH-0260,P-554,1/1/1900,10/6/20517,13600000,4/26/24241,NV00059,CN DN
1361,2/28/2017,ĐH0000041,KH-0542,P-555,1/1/1900,8/3/5048,2300000,1/11/6308,NV00015,CN DN
1362,3/1/2017,ĐH0000046,KH-0483,P-556,1/1/1900,2/3/22708,15200000,7/8/28950,NV00007,CN DN
1363,3/2/2017,ĐH0000017,KH-0543,P-007,1/1/1900,1/15/24077,16200000,2/27/30730,NV00017,CN DN
1366,3/5/2017,ĐH0000023,KH-0544,P-032,1/1/1900,10/5/25385,17156000,11/30/30082,NV00086,CN DN
1369,3/8/2017,ĐH0000037,KH-0068,P-062,1/1/1900,9/5/4111,1615600,5/7/4996,NV00017,CN DN
1371,3/10/2017,ĐH0000079,KH-0444,P-016,1/1/1900,10/1/22105,14760000,1/19/30188,NV00007,CN DN
1373,3/12/2017,ĐH0000088,KH-0356,P-506,1/1/1900,8/11/2666,560000,12/7/2819,NV00046,CN DN
1375,3/14/2017,ĐH0000095,KH-0545,P-381,1/1/1900,11/30/7238,3900000,6/25/9374,NV00009,CN DN
1377,3/16/2017,ĐH0000102,KH-0546,P-558,1/1/1900,3/14/10004,5920000,11/18/13245,NV00007,CN DN
1379,3/18/2017,ĐH0000118,KH-0547,P-559,1/1/1900,10/28/33522,23100000,9/2/43009,NV00081,CN DN
1387,3/26/2017,ĐH0000147,KH-0549,P-018,1/1/1900,7/5/10387,6200000,1/3/12085,NV00095,CN DN
1390,3/29/2017,ĐH0000070,KH-0550,P-015,1/1/1900,12/8/12440,7700000,2/15/14549,NV00086,CN DN
1391,3/30/2017,ĐH0000177,KH-0551,P-016,1/1/1900,3/26/21996,14680000,2/7/28025,NV00015,CN DN
1397,4/5/2017,ĐH0000219,KH-0552,P-473,1/1/1900,7/7/52004,36600600,4/28/72046,NV00017,CN DN
1398,4/6/2017,ĐH0000225,KH-0537,P-546,1/1/1900,6/21/2584,500000,10/25/2789,NV00068,CN DN
1400,4/8/2017,ĐH0000258,KH-0553,P-459,1/1/1900,132540000,265080000,159048000,NV00095,CN DN
1404,4/12/2017,ĐH0000282,KH-0251,P-015,1/1/1900,3/14/12438,7698000,8/30/15599,NV00068,CN DN
1407,4/15/2017,ĐH0000300,KH-0555,P-045,1/1/1900,9/10/16684,10800000,8/19/19641,NV00095,CN DN
1415,4/23/2017,ĐH0000383,KH-0176,P-045,1/1/1900,10/25/14562,9250000,5/19/17095,NV00046,CN DN
1424,5/2/2017,ĐH0000455,KH-0332,P-017,1/1/1900,7/8/12988,8100000,12/6/17423,NV00011,CN DN

In [371]:
du_lieu_ban_hang[~du_lieu_ban_hang['Số lượng bán'].str.isdecimal()]['Số lượng bán'].unique().tolist()
for i in du_lieu_ban_hang[~du_lieu_ban_hang['Số lượng bán'].str.isdecimal()]['Số lượng bán'].unique().tolist():
    index  = du_lieu_ban_hang[du_lieu_ban_hang['Số lượng bán'] == i].index
    du_lieu_ban_hang.loc[index, 'Số lượng bán'] = '1'

In [370]:
du_lieu_ban_hang.loc[du_lieu_ban_hang['Số lượng bán'] == '1/1/1900' , 'Số lượng bán'] = '1'

In [379]:
du_lieu_ban_hang['Doanh thu'] = du_lieu_ban_hang['Doanh thu'].astype('int')

In [384]:
du_lieu_ban_hang['Đơn giá'] = du_lieu_ban_hang['Đơn giá'].astype('int')

In [386]:
du_lieu_ban_hang['Số lượng bán'] = du_lieu_ban_hang['Số lượng bán'].astype('int')

In [ ]:
#BACK UP DATA
back_up = du_lieu_ban_hang.copy()

In [414]:
map_dict = du_lieu_ban_hang[du_lieu_ban_hang['Giá vốn hàng hóa'].str.isdecimal()].\
        groupby('Mã Sản Phẩm' , as_index = False)['Giá vốn hàng hóa'].mean()

In [417]:
map_dict_1 =map_dict.set_index('Mã Sản Phẩm')['Giá vốn hàng hóa'].to_dict()

In [418]:
du_lieu_ban_hang['Giá vốn hàng hóa'] = du_lieu_ban_hang['Mã Sản Phẩm'].map(map_dict_1)

In [432]:
du_lieu_ban_hang['Giá vốn hàng hóa'].unique()

array([2.27500000e+007, 2.65205100e+007, 2.56666694e+042, 2.25288030e+020,
       7.54000138e+035, 4.58250000e+006, 6.42777820e+064, 1.16060012e+037,
       2.42125023e+028,             nan, 2.96470621e+124, 2.07444900e+006,
       2.80800025e+013,             inf, 1.76727291e+075, 2.03914306e+047,
       1.74145847e+044, 2.07200000e+006, 5.65500051e+080, 7.78750008e+126,
       1.49800000e+006, 1.26176484e+122, 8.08950096e+029, 2.62843770e+118,
       3.32500027e+131, 1.11020000e+007, 8.46318469e+100, 6.19500000e+007,
       2.38000000e+006, 5.84025059e+054, 3.66240000e+006, 7.50000000e+006,
       5.28016687e+023, 3.25000000e+006, 2.87140000e+006, 1.27062000e+007,
       3.95500046e+073, 8.48076932e+102, 8.88485000e+006, 9.17000000e+006,
       4.37500350e+011, 7.50001625e+010, 1.07887503e+030, 2.32555765e+054,
       3.66660032e+021, 1.09200000e+007, 2.90500000e+006, 3.97727670e+162,
       7.96252169e+023, 5.29846272e+096, 7.56000000e+006, 2.40500000e+006,
       2.73000030e+013, 2.37250000e+007, 3.80000031e+282, 4.22500488e+011,
       6.96431348e+080, 2.38000020e+020, 3.60000179e+012, 9.24000845e+029,
       2.03225948e+196, 1.62000000e+006, 1.57780000e+008, 6.40250000e+006,
       8.12500910e+058, 2.53022406e+037, 2.56338337e+021, 2.32722000e+007,
       5.73400070e+020, 8.26000000e+006, 1.69750000e+006, 2.38680000e+006,
       1.44660000e+006, 4.64340000e+006, 4.70160000e+006, 9.13920000e+005,
       2.26153865e+100, 2.33333354e+086, 5.04360018e+014, 1.71363808e+137,
       3.03334904e+017, 4.35500028e+014, 1.61000000e+007, 8.16000000e+006,
       3.46200000e+006, 6.10018501e+016, 2.15625002e+015, 8.63310007e+022,
       1.24930000e+007, 4.64750005e+014, 4.06800000e+007, 1.54375004e+030,
       3.96500000e+006, 5.29666686e+023, 1.24416500e+007, 2.07046688e+020,
       9.40875000e+006, 5.06666679e+071, 2.73875023e+055, 7.01400000e+006,
       1.98900031e+020, 1.56000018e+020, 6.00000067e+026, 2.10000084e+012,
       9.39250278e+012, 1.63677504e+028, 1.82000002e+015, 8.40000000e+006,
       1.75526014e+035, 6.22500059e+046, 1.73407000e+007, 1.01604000e+007,
       3.49544118e+008, 0.00000000e+000, 4.56300000e+008, 1.66725000e+008,
       1.60272000e+008, 2.63250000e+007, 1.32947399e+008, 2.28150000e+008,
       1.92102400e+008, 5.60000100e+043, 1.20000000e+007, 3.02750029e+013,
       5.17400000e+006, 1.21620000e+007, 9.69000000e+006, 1.72350002e+023,
       3.16290000e+007, 2.40987524e+058, 9.52250093e+072, 1.21345001e+015,
       2.64062744e+047, 2.23795000e+006, 1.82000000e+007, 2.65135024e+074,
       1.70625025e+013, 4.55700000e+006, 5.60001620e+017, 1.68000259e+029,
       8.01666736e+021, 9.59000000e+006, 4.50000000e+005, 2.30750002e+047,
       1.60090000e+007, 3.82200000e+006, 3.43000000e+005, 5.11000000e+006,
       2.80800000e+007, 5.20000000e+005, 2.94000000e+006, 2.73000000e+006,
       1.13148000e+006, 1.39750000e+006, 1.33250000e+007, 6.50000000e+007,
       8.45000000e+005, 2.27500000e+006, 2.19327000e+008, 6.01992000e+007,
       1.07250000e+008, 1.32000000e+007, 1.63333335e+023, 3.53000025e+022,
       8.93100000e+005, 2.04400000e+006, 2.10000320e+096, 2.66666895e+134,
       1.22500000e+006, 3.81818895e+064, 1.01400000e+006, 4.52368000e+007,
       1.68343500e+008, 9.83100011e+014, 1.26000000e+005, 1.70919000e+007,
       1.19196000e+008, 2.38392000e+007, 2.83710008e+013, 3.63300000e+007,
       1.25000023e+022, 3.00000152e+116, 3.95200179e+020, 3.09000000e+007,
       9.96900010e+014, 8.75000750e+010, 6.02000000e+006, 1.43000000e+006,
       5.85001430e+010, 9.91250000e+005, 1.54726000e+007, 1.12000000e+007,
       4.96800000e+005, 3.50700000e+006, 4.42000004e+038, 1.05000000e+006,
       2.86000031e+040, 1.75500000e+006, 7.80000780e+042, 1.80000002e+046,
       5.78500000e+006, 1.41750036e+013, 2.88000000e+007, 3.72000000e+006,
       1.20000000e+006, 9.73000000e+006, 2.23000075e+042, 2.66695000e+006,
       2.87301002e+023, 5.25346256e+031, 1.10600015e+013, 1.80000855e+010,
       3.50000000e+005, 3.69600000e+007, 4.11833337e+022, 5.13600000e+007,
       1.84166752e+019, 3.67800000e+006, 4.13000000e+005, 2.01500000e+006,
       2.81400000e+007, 1.93050000e+006, 1.36500000e+007, 1.28400000e+007,
       1.10600000e+006, 1.59250000e+007, 4.14000000e+006, 2.00200000e+006,
       7.72200000e+006, 6.30000064e+013, 5.10090000e+007, 1.05750000e+007,
       5.79000000e+006, 1.40000000e+006, 1.45320000e+007, 1.31600000e+006,
       2.62800000e+007, 3.93250000e+007, 1.65184500e+007, 9.18645035e+014,
       1.26700000e+007, 5.28000000e+005, 2.59000070e+019, 4.52393500e+007,
       5.28500000e+006, 9.00000000e+006, 4.20000000e+005, 1.56648100e+008,
       7.02650000e+006, 3.29000000e+006, 3.11130000e+007, 2.87280000e+006,
       3.73750040e+013, 1.57500158e+011, 9.67200000e+007, 4.80000000e+006,
       1.29850000e+007, 1.50150000e+007, 3.48000000e+006, 2.53750002e+015,
       1.34400000e+007, 2.91667542e+036, 1.17272700e+006, 2.37000000e+006,
       1.95000027e+013, 2.24014000e+007, 1.06050000e+007, 5.53636300e+006,
       1.06656000e+007, 6.91080000e+006, 3.59400000e+006, 9.50300000e+006,
       2.86286000e+007, 1.01955000e+007, 1.42110000e+007, 4.17088000e+007,
       1.28100000e+007, 1.31820000e+006, 2.84550011e+014, 7.11678000e+007,
       5.39500000e+006, 4.44166671e+022, 2.02300000e+007, 1.57500005e+015,
       9.71700000e+006, 3.08000000e+006, 2.56100000e+007, 7.77272700e+006,
       2.72300000e+006, 4.29000000e+005, 2.28000000e+006, 9.10000000e+006,
       1.23000000e+007, 2.06700000e+006, 3.30000007e+014, 2.43000006e+014,
       1.04650054e+012, 4.46880001e+016, 3.00000000e+006, 8.40000010e+014,
       3.12975000e+007, 1.14000000e+007, 2.79500000e+007, 1.24800000e+007,
       2.34000057e+041, 1.58600000e+007, 1.30900000e+007, 2.56750036e+013,
       1.92000000e+005, 4.76125000e+007, 7.47500012e+014, 3.84000000e+006,
       3.61400000e+006, 1.19454720e+007, 3.18500000e+005, 2.85187500e+008,
       1.17856200e+008, 2.45700000e+008, 2.21760000e+007, 5.28000000e+006,
       4.14791002e+016, 5.40540075e+019, 6.84530147e+020, 4.92520000e+007,
       5.13912000e+007, 3.31680000e+006, 2.95170003e+063, 1.81104000e+007,
       5.77500488e+051, 1.45200000e+006, 7.50000131e+012, 3.36000000e+005,
       8.10001215e+010, 6.30500102e+012, 1.02200000e+008, 1.50930015e+043,
       4.05600000e+007, 9.55080000e+006, 3.78000000e+007, 1.60300000e+007,
       3.25000031e+036, 1.77000000e+006, 1.16200000e+007, 1.72900000e+007,
       5.90100000e+007, 3.86400000e+007, 3.36000000e+006, 7.80000000e+005,
       5.72600000e+006, 2.79000003e+014, 4.68000000e+005, 9.99180000e+006,
       2.50320000e+007, 3.00000000e+005, 4.15200000e+005, 6.90000473e+025,
       2.09950000e+007, 7.59080000e+007, 2.08000000e+007, 6.12000063e+028,
       3.84800000e+006, 1.95272700e+006, 1.12800000e+007, 3.68666986e+019,
       2.86300000e+006, 7.42989853e+028, 1.22571495e+049, 8.62800000e+006,
       3.70351800e+008, 8.14775000e+007, 9.38000000e+005, 6.52600000e+005,
       4.05000000e+007, 3.22200000e+006, 5.42856600e+007, 2.98956000e+006,
       1.86900000e+007, 1.17000002e+015, 6.92208000e+007, 7.41468000e+007,
       8.88000173e+019, 4.95600071e+033, 1.93500032e+026, 7.77000067e+034,
       1.44000144e+017, 5.77980027e+045, 1.56000000e+007, 1.90400000e+006,
       8.86909233e+079, 1.08000000e+006, 1.05120000e+007, 1.34550000e+006,
       6.08400000e+006, 4.99800000e+006, 5.69400000e+006, 2.50200000e+007,
       3.80640001e+031, 2.06784000e+007, 6.67800000e+005, 8.43609000e+007,
       1.59600000e+007, 1.48200000e+007, 5.53560000e+006, 8.19000000e+006,
       3.13200034e+033, 1.36944500e+007, 5.33405860e+007, 6.87750000e+007,
       2.49000004e+021, 3.45835000e+007, 1.68900000e+006, 2.96725000e+007,
       8.28750000e+007, 1.91750000e+007, 1.95000029e+026, 1.86165000e+007,
       2.43000000e+007, 1.43500000e+007, 1.87620000e+007, 1.11230000e+008,
       4.65500000e+006, 1.41000000e+006, 9.55500247e+012, 4.20000000e+007,
       1.87250000e+007, 6.36900000e+007, 1.44028501e+015, 3.90000019e+013,
       1.47303900e+007, 3.85000000e+006, 4.85100000e+007, 3.31200000e+006,
       9.16788906e+067, 7.98525000e+008, 2.52000000e+006, 6.90240000e+007,
       3.85728000e+006, 1.07065000e+008, 8.98170001e+111, 4.62161700e+007,
       3.63000000e+007, 2.20500000e+007, 7.80000000e+006, 2.48704200e+007,
       7.86500000e+006, 2.94125029e+013, 3.88500000e+007, 1.30797352e+022,
       1.02690000e+007, 4.91850000e+007, 2.31192003e+015, 8.00000032e+045,
       1.26600000e+007, 4.29000000e+007, 2.95920001e+015, 3.94800000e+007,
       4.60600000e+008, 1.83960000e+007, 3.12900006e+014, 1.03500001e+015,
       2.16000000e+006, 8.02800000e+007, 9.28200000e+008, 1.20120000e+016,
       1.17000002e+015, 6.84000000e+006, 4.19250032e+021, 4.95820000e+007,
       3.96812000e+007, 5.81168000e+007, 4.16000000e+006, 1.23396000e+007,
       4.61890000e+007, 1.46160000e+007, 1.62500000e+006, 6.30856800e+008,
       4.13805000e+008, 2.24323200e+007, 4.32000000e+007, 2.25446000e+008,
       1.95000000e+007, 2.80840000e+007, 6.29850000e+007, 1.11171203e+015,
       8.76486002e+015, 4.72334660e+007, 5.16880000e+007, 6.58980000e+007,
       2.94545400e+006, 7.27776000e+007, 2.19960000e+008, 1.36656000e+008,
       1.48368000e+007, 4.09240002e+015, 3.59736000e+007, 1.02960000e+007,
       5.34312000e+007, 6.78300000e+007, 4.41000000e+006, 8.67000000e+006,
       1.12868000e+007, 1.03133347e+020, 2.14200036e+013, 8.89525000e+007,
       2.23787200e+008, 4.63606000e+007, 8.33690009e+014, 3.38000000e+006,
       1.08276000e+007, 1.64656800e+007, 1.71468000e+006, 2.47716000e+006,
       1.60083000e+008, 5.76000000e+006, 4.64100000e+007, 1.65750000e+006,
       1.74850000e+007, 2.52000011e+014, 9.75000000e+006, 9.54799300e+006,
       7.51800000e+006, 7.02000000e+006, 2.39400000e+007, 2.21200000e+007,
       1.81200000e+007, 5.88380000e+007, 2.56620000e+007, 1.10890000e+007,
       2.79300000e+007, 2.71544000e+007, 2.31400000e+007, 1.96560000e+006,
       3.23024000e+008, 3.74400000e+006, 6.17500003e+015, 9.91900000e+007,
       4.35120000e+007, 1.25580000e+007, 1.74000000e+006, 6.60000000e+005,
       3.60000000e+005, 4.97000000e+007, 1.57500000e+008, 9.78250000e+007,
       6.82500000e+007, 6.60000000e+004])

In [440]:
du_lieu_ban_hang['Giá vốn hàng hóa'].replace('inf',None , inplace=True)

In [442]:
du_lieu_ban_hang['Giá vốn hàng hóa'].fillna(value =du_lieu_ban_hang['Giá vốn hàng hóa'].median() )

4       2.275000e+07
5       2.275000e+07
6       2.652051e+07
7       2.566667e+42
8       2.252880e+20
            ...
2626    1.575000e+08
2627    9.782500e+07
2628    6.825000e+07
2629             inf
2631    6.600000e+04
Name: Giá vốn hàng hóa, Length: 2108, dtype: float64

In [476]:
df1 = du_lieu_ban_hang[~du_lieu_ban_hang['Giá vốn hàng hóa'].str.contains('/')]['Giá vốn hàng hóa']
df1.median()

7860300.0

In [477]:
index1 = du_lieu_ban_hang[du_lieu_ban_hang['Giá vốn hàng hóa'].str.contains('/')].index
du_lieu_ban_hang.loc[index1 , 'Giá vốn hàng hóa'] = df1.median()

In [382]:
du_lieu_ban_hang['Đơn giá'] = du_lieu_ban_hang['Doanh thu'] / du_lieu_ban_hang['Đơn giá']

In [101]:
du_lieu_ban_hang['Đơn giá'].loc[2631].replace(',','').replace('.00','').strip()

'110000'

In [102]:
du_lieu_ban_hang['Số lượng bán'].replace()

4       12/31/1899
5       12/31/1899
6       12/31/1899
7                1
8                1
           ...
2627        20.00
2628     1/14/1900
2629         1.00
2630    12/31/1899
2631         1.00
Name: Số lượng bán, Length: 2624, dtype: object

In [475]:
du_lieu_ban_hang = back_up.copy()

In [103]:
du_lieu_ban_hang['Mã Sản Phẩm'].isna().sum()

0

In [478]:
du_lieu_ban_hang['Giá vốn hàng hóa'] = du_lieu_ban_hang['Giá vốn hàng hóa'].astype('float')

In [484]:
du_lieu_ban_hang[du_lieu_ban_hang['Đơn giá'] == 0].index
du_lieu_ban_hang.drop(du_lieu_ban_hang[du_lieu_ban_hang['Đơn giá'] == 0].index , axis=0, inplace=True)

In [492]:
du_lieu_ban_hang

,Ngày hạch toán,Đơn hàng,Mã KH,Mã Sản Phẩm,Số lượng bán,Đơn giá,Doanh thu,Giá vốn hàng hóa,Mã nhân viên bán,Chi nhánh
4,2017-01-03,ĐH0000737,KH-0001,P-001,1,27300000,27300000,7860300.0,NV00078,CN DN
5,2017-01-04,ĐH0000733,KH-0002,P-001,1,22269560,22269560,7860300.0,NV00078,CN DN
6,2017-01-05,ĐH0000734,KH-0002,P-002,1,43680840,43680840,7860300.0,NV00078,CN DN
7,2017-01-06,ĐH0000764,KH-0003,P-003,1,2200000,2200000,1540000.0,NV00051,CN HCM
8,2017-01-07,ĐH0000768,KH-0002,P-004,1,11264400,11264400,6758640.0,NV00078,CN HCM
...,...,...,...,...,...,...,...,...,...,...
2626,2019-03-29,ĐH10541,KH-0786,P-795,1,225000000,225000000,157500000.0,NV00046,CN DN
2627,2019-03-29,ĐH10541,KH-0786,P-796,20,7525000,150500000,97825000.0,NV00046,CN HCM
2628,2019-03-29,ĐH10541,KH-0786,P-797,1,97500000,97500000,68250000.0,NV00046,CN DN
2629,2019-03-29,ĐH10434,KH-0176,P-018,1,2930000,2930000,1904500.0,NV00095,CN HCM
2631,2019-03-29,ĐH10434,KH-0176,P-799,1,110000,110000,66000.0,NV00095,CN HN

In [491]:
check_info_df(data = du_lieu_ban_hang)

,date_type,count_unique,not_null_value,null_value,percentage_of_null
Ngày hạch toán,object,1190,2096,0,0.0
Đơn hàng,object,1307,2096,0,0.0
Mã KH,object,711,2096,0,0.0
Mã Sản Phẩm,object,681,2096,0,0.0
Số lượng bán,int32,80,2096,0,0.0
Đơn giá,int32,1309,2096,0,0.0
Doanh thu,int32,1486,2096,0,0.0
Giá vốn hàng hóa,float64,1564,2096,0,0.0
Mã nhân viên bán,object,45,2096,0,0.0
Chi nhánh,category,3,2096,0,0.0

In [490]:
du_lieu_ban_hang['Ngày hạch toán'] = pd.to_datetime(du_lieu_ban_hang['Ngày hạch toán']).dt.date

In [488]:
du_lieu_ban_hang['Chi nhánh'] = du_lieu_ban_hang['Chi nhánh'].astype('category')

In [523]:
du_lieu_ban_hang.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\du_lieu_ban_hang.csv', encoding = 'utf-16')

# Khách hàng - Cần sửa

In [503]:
khach_hang.columns = khach_hang.loc[1]

In [505]:
khach_hang.columns.name = None

In [509]:
khach_hang = khach_hang.loc[2:len(khach_hang)]

In [524]:
khach_hang.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\khach_hang.csv', encoding = 'utf-16')

# KPI - Done

In [525]:
kpi.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\kpi.csv', encoding = 'utf-16')

# Nhân viên - Cần sửa

In [511]:
nhan_vien.columns = nhan_vien.loc[3]
nhan_vien.columns.name = None
nhan_vien = nhan_vien.loc[3:len(nhan_vien)]

In [513]:
nhan_vien = nhan_vien.loc[4:len(nhan_vien)]

In [526]:
nhan_vien.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\nhan_vien.csv', encoding = 'utf-16')

# Danh sách sản phẩm - Cần Sửa

In [515]:
san_pham.columns = san_pham.loc[3]
san_pham.columns.name = None
san_pham = san_pham.loc[4:len(nhan_vien)]

In [527]:
san_pham.to_csv(r'C:\Users\Admin\Downloads\Python_tableau_final\san_pham.csv', encoding = 'utf-16')

# Kết thúc và xuất file sau khi cleaning data